- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: IaC
      name: LinuxVM
      vm_size: Standard_DS1_v2
      admin_username: vmsilvamolina
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/vmsilvamolina/.ssh/authorized_keys
          key_data: ""
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
